### ISSUE TITLE
don't seem to be able to run puphpeteer with cron job

### ISSUE THREAD

**Issue by jpajavonGit** [nesk/puphpeteer#15]
Hi hope you can help on that one : 

**Describe the bug**
i have some code using puphpeteer that can run from the prompt on a ubuntu16.04 remote server, but 
trying to launch the exact same program on a cron job  result with  an error
i can reproduce the same error with the code example given in your doc

**Reproducible example**
on the "crontab -e " i enter :
 /usr/bin/php /home/level1/level2/Phantom/pupetteer/petitTest.php

petitTest.php : 
use Nesk\Puphpeteer\Puppeteer;

$puppeteer = new Puppeteer;
$browser = $puppeteer->launch();

$page = $browser->newPage();
$page->goto('https://example.com');
$page->screenshot(['path' => 'example.png']);

$browser->close();
```php
**Expected behavior**
Again running that program directly from command line is fine but not on the cron job

**Generated logs**

```
PHP Fatal error:  Uncaught Symfony\Component\Process\Exception\ProcessFailedException: The command "'node' '/home/level1/level2/Phantom/pupetteer/vendor/nesk/rialto/src/node-process/serve.js' '/home/level1/level2/Phantom/pupetteer/vendor/nesk/puphpeteer/src/PuppeteerConnectionDelegate.js' '{"idle_timeout":60}'" failed.

Exit Code: 1(General error)

Working directory: /home/level1

Output:
================

Error Output:
================
/home/level1/level2/Phantom/pupetteer/vendor/nesk/rialto/src/node-process/Server.js:17
    constructor(connectionDelegate, options = {})
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/home/level1/level2/Phantom/pupetteer/vendor/n in /home/level1/level2/Phantom/pupetteer/vendor/nesk/rialto/src/ProcessSupervisor.php on line 232
```

**Environment :**
 - OS:  Ubuntu 16.04
 - Node version: v10.6.0
 - PHP version: PHP 7.2.7-1+ubuntu16.04.1+deb.sury.org+1 (cli)
My Node package manager is:
 - NPM (6.2.0)
 
**Additional context**
Add any other context about the problem here.

**Comment by jpajavonGit** [comment]
Sorted:
Another nodejs was also installed on the system and was symlinked.
had to remove old nodejs and recreate symlink.
