### ISSUE TITLE
page->pdf() - Protocol error (IO.read): Target closed.

### ISSUE THREAD

**Issue by antman3351** [nesk/puphpeteer#85]
**Describe the bug**
Calling page->pdf() throws error Protocol error (IO.read): Target closed.

($page->screenshot() works, so the page loads)

Stack trace:
```
#0 \vendor\nesk\rialto\src\ProcessSupervisor.php(453): Nesk\Rialto\ProcessSupervisor->unserialize(Array)
#1 \vendor\nesk\rialto\src\ProcessSupervisor.php(382): Nesk\Rialto\ProcessSupervisor->readNextProcessValue(true)
#2 \vendor\nesk\rialto\src\Traits\CommunicatesWithProcessSupervisor.php(84): Nesk\Rialto\ProcessSupervisor->executeInstruction(Object(Nesk\Rialto\Instruction)) #3 \vendor\nesk\rialto\src\Traits\CommunicatesWithProcessSupervisor.php(100): Nesk\Rialto\Data\BasicResource->proxyAction('call', 'pdf', Array)
#4 \modules\forplus_mod\modules\printtemplate2\converters\htmlToPdf\HtmlToPdf.php(29): Nesk\Rialto\Data\BasicResource->__call('pdf', Array)
```

**Reproducible example**
```php
$puppeteer = new Puppeteer(
            [
                'executable_path' => 'C:\laragon\bin\nodejs\node-v12\node.exe',
                'log_node_console' => true,
                'log_browser_console' => true,
            ]
        );

        $browser = $puppeteer->launch( [ 'headless' => true ] );

        $page = $browser->newPage();
        $page->goto( 'http://test.test', [ "waitUntil" => "networkidle0" ] );
        $page->pdf( [ "path" => 'php.pdf', 'format' => 'A4' ] );
        $browser->close();
```

**Expected behavior**
Find a nice pdf file 😎

**Generated logs**
```
[2020-03-27 10:34:31] INFO: Applying options...
[2020-03-27 10:34:31] DEBUG: Options applied and merged with defaults
[2020-03-27 10:34:31] INFO: Starting process with command line: C:\laragon\bin\nodejs\node-v12\node.exe C:\laragon\www\softcodex\totalgest\3.2.0\node_modules\@nesk\rialto\src\node-process\serve.js C:\laragon\www\softcodex\totalgest\3.2.0\vendor\nesk\puphpeteer\src\PuppeteerConnectionDelegate.js "{""idle_timeout"":60,""log_node_console"":true,""log_browser_console"":true}"
[2020-03-27 10:34:31] INFO: Process started with PID 5040
[2020-03-27 10:34:31] DEBUG: Sending an instruction to the port 7674...
[2020-03-27 10:34:32] DEBUG: Received data from the port 7674...
[2020-03-27 10:34:32] DEBUG: Received data from the port 7674...
[2020-03-27 10:34:32] DEBUG: Sending an instruction to the port 7674...
[2020-03-27 10:34:32] DEBUG: Sending an instruction to the port 7674...
[2020-03-27 10:34:32] DEBUG: Received data from the port 7674...
[2020-03-27 10:34:32] DEBUG: Sending an instruction to the port 7674...
[2020-03-27 10:34:33] DEBUG: Received data from the port 7674...
[2020-03-27 10:34:33] DEBUG: Received data from the port 7674...
[2020-03-27 10:34:33] DEBUG: Sending an instruction to the port 7674...
[2020-03-27 10:34:42] ERROR: Received data on stderr: {"__rialto_error__":true,"message":"Protocol error (IO.read): Target closed.","stack":"Error: Protocol error (IO.read): Target closed.\n    at C:\\laragon\\www\\softcodex\\totalgest\\3.2.0\\node_modules\\puppeteer\\lib\\Connection.js:183:56\n    at new Promise (<anonymous>)\n    at CDPSession.send (C:\\laragon\\www\\softcodex\\totalgest\\3.2.0\\node_modules\\puppeteer\\lib\\Connection.js:182:12)\n    at Function.readProtocolStream (C:\\laragon\\www\\softcodex\\totalgest\\3.2.0\\node_modules\\puppeteer\\lib\\helper.js:238:37)\n    at async Page.pdf (C:\\laragon\\www\\softcodex\\totalgest\\3.2.0\\node_modules\\puppeteer\\lib\\Page.js:943:12)\n    at async PuppeteerConnectionDelegate.handleInstruction (C:\\laragon\\www\\softcodex\\totalgest\\3.2.0\\vendor\\nesk\\puphpeteer\\src\\PuppeteerConnectionDelegate.js:36:21)\n  -- ASYNC --\n    at Page.<anonymous> (C:\\laragon\\www\\softcodex\\totalgest\\3.2.0\\node_modules\\puppeteer\\lib\\helper.js:111:15)\n    at Instruction.callResourceMethod (C:\\laragon\\www\\softcodex\\totalgest\\3.2.0\\node_modules\\@nesk\\rialto\\src\\node-process\\Instruction.js:186:40)\n    at Instruction.execute (C:\\laragon\\www\\softcodex\\totalgest\\3.2.0\\node_modules\\@nesk\\rialto\\src\\node-process\\Instruction.js:161:31)\n    at PuppeteerConnectionDelegate.handleInstruction (C:\\laragon\\www\\softcodex\\totalgest\\3.2.0\\vendor\\nesk\\puphpeteer\\src\\PuppeteerConnectionDelegate.js:36:39)\n    at Connection.handleSocketData (C:\\laragon\\www\\softcodex\\totalgest\\3.2.0\\node_modules\\@nesk\\rialto\\src\\node-process\\Connection.js:65:23)\n    at Socket.<anonymous> (C:\\laragon\\www\\softcodex\\totalgest\\3.2.0\\node_modules\\@nesk\\rialto\\src\\node-process\\Connection.js:49:18)\n    at Socket.emit (events.js:200:13)\n    at addChunk (_stream_readable.js:294:12)\n    at readableAddChunk (_stream_readable.js:271:13)\n    at Socket.Readable.push (_stream_readable.js:210:10)"}ERROR: The process "7124" not found.

[2020-03-27 10:34:42] WARNING: The process cannot because be stopped because it's no longer running
```
**Environment (please complete the following information):**
 - OS: Windows 10
 - Node version: 12.5.0 (installed with laragon)
 - PHP version 7.2, 7.3, 7.4 (installed with laragon)

My Node package manager is:
 - NPM 6.9.0

**Additional context**
Calling puppeteer directly from node works
```js
const puppeteer = require('puppeteer');

(async () => {
  const browser = await puppeteer.launch({ headless: true });
  const page = await browser.newPage();
  await page.goto('http://test.test', {waitUntil: 'networkidle0'});
  const pdf = await page.pdf({ format: 'A4', path: 'node.pdf' });
 
  await browser.close();
  return pdf
})();
```

I tried using puppeteer 2.1.1, it didn't make any difference.
Tried setting timeouts  `'read_timeout' => 1000` and `'idle_timeout' => 1000`
http://test.test -> is just phpinfo page. I also tried a blank page,  no difference.

Thanks!

**Comment by Feniksss** [comment]
same issue...

**Comment by 50l3r** [comment]
same isue

**Comment by 50l3r** [comment]
If i set 'userDataDir' to browser i have another error:

```
<p>Type: Socket\Raw\Exception</p>
<p>Message: Socket operation failed: No se puede completar de forma inmediata una operación de desbloqueo de socket.
 (SOCKET_EWOULDBLOCK)</p>
<p>Filename: D:\Git\gestios\gestios-sandbox\vendor\clue\socket-raw\src\Exception.php</p>
<p>Line Number: 59</p>


	<p>Backtrace:</p>
	
		
			<p style="margin-left:10px">
			File: D:\Git\gestios\gestios-sandbox\vendor\clue\socket-raw\src\Exception.php<br />
			Line: 28<br />
			Function: createFromCode			</p>
		
	
		
			<p style="margin-left:10px">
			File: D:\Git\gestios\gestios-sandbox\vendor\clue\socket-raw\src\Socket.php<br />
			Line: 247<br />
			Function: createFromSocketResource			</p>
		
	
		
			<p style="margin-left:10px">
			File: D:\Git\gestios\gestios-sandbox\vendor\nesk\rialto\src\ProcessSupervisor.php<br />
			Line: 409<br />
			Function: read			</p>
		
	
		
			<p style="margin-left:10px">
			File: D:\Git\gestios\gestios-sandbox\vendor\nesk\rialto\src\ProcessSupervisor.php<br />
			Line: 382<br />
			Function: readNextProcessValue			</p>
		
	
		
			<p style="margin-left:10px">
			File: D:\Git\gestios\gestios-sandbox\vendor\nesk\rialto\src\Traits\CommunicatesWithProcessSupervisor.php<br />
			Line: 84<br />
			Function: executeInstruction			</p>
		
	
		
			<p style="margin-left:10px">
			File: D:\Git\gestios\gestios-sandbox\vendor\nesk\rialto\src\Traits\CommunicatesWithProcessSupervisor.php<br />
			Line: 100<br />
			Function: proxyAction			</p>
		
	
		
			<p style="margin-left:10px">
			File: D:\Git\gestios\gestios-sandbox\application\controllers\nest\Facturas.php<br />
			Line: 168<br />
			Function: __call			</p>
		
	
		
	
		
			<p style="margin-left:10px">
			File: D:\Git\gestios\gestios-sandbox\index.php<br />
			Line: 291<br />
			Function: require_once			</p>
		
	

</div>
```

Thats my code:

```
$puppeteer = new Puppeteer;
$browser   = $puppeteer->launch([
    '--no-sandbox',
    '--disable-setuid-sandbox',
    'headless'    => true,
    'userDataDir' => TMPPATH,
]);

$page = $browser->newPage();

$page->goto(base_url('/nest/facturas/html/' . $id), ['timeout' => 90000]);
$page->pdf(['path' => $tmpFilePath, 'format' => 'A4']);

$browser->close();
```

I've enabled sockets extension

**Comment by ismaxim** [comment]
+1 The same issue

**Comment by maximgrynykha** [comment]
Addressed to @nesk if you would have time, please try to fix it🙏

+1 The same issue (Protocol error (IO.read): Target closed) 🐞

Environment:

- OS: Windows 10 Pro 64bit
- PHP: v7.3(tested on v7.4)
- NODE: v14.15.0
- NPM: v6.14.8
- LocalServer: OpenServer v5.3.7

CODE:

```php
<?php

require "vendor/autoload.php";

use Nesk\Puphpeteer\Puppeteer;

$puppeteer = new Puppeteer([
    'executable_path' => 'C:\Program Files\nodejs\node.exe',

    // How much time (in seconds) the process can stay 
    // inactive before being killed (set to null to disable)
    'idle_timeout' => 60,

    // How much time (in seconds) an instruction can take 
    // to return a value (set to null to disable)
    'read_timeout' => 30,

    'log_node_console' => false,
    'log_browser_console' => false,

    'debug' => true,
]);

$browser = $puppeteer->launch([
    'headless' => true,
    'args' => ['--no-sandbox', '--disable-setuid-sandbox'],
]);

$page = $browser->newPage();
$page->goto('https://google.com', ['waitUntil' => 'load']);

// Loading extension only works when headless is set to false. 
// And at the same time I need to set headless to true for PDF
// https://github.com/puppeteer/puppeteer/issues/1829

$page->pdf([
    'path' => "google.pdf", 
    'format' => 'A4'
]);
// sleep(10);

$browser->close();
```


ERRORS:

```plaintext
Fatal error: 
    Uncaught Nesk\Rialto\Exceptions\Node\FatalException: Protocol error (IO.read): Target closed. in C:\OpenServer\domains\example\vendor\nesk\rialto\src\ProcessSupervisor.php:307 
    
    Stack trace: 
        #0 C:\OpenServer\domains\example\vendor\nesk\rialto\src\ProcessSupervisor.php(423): Nesk\Rialto\ProcessSupervisor->checkProcessStatus() 

        #1 C:\OpenServer\domains\example\vendor\nesk\rialto\src\ProcessSupervisor.php(382): Nesk\Rialto\ProcessSupervisor->readNextProcessValue(true) 
        
        #2 C:\OpenServer\domains\example\vendor\nesk\rialto\src\Traits\CommunicatesWithProcessSupervisor.php(84): Nesk\Rialto\ProcessSupervisor->executeInstruction(Object(Nesk\Rialto\Instruction)) 
        
        #3 C:\OpenServer\domains\example\vendor\nesk\rialto\src\Traits\CommunicatesWithProcessSupervisor.php(100): Nesk\Rialto\Data\BasicResource->proxyAction('call', 'pdf', Array) 
        
        #4 C:\OpenServer\domains\example\index.php(49): Nesk\Rialto\Data\BasicResource->__call('pdf', Array) #5 {main} thrown in C:\OpenServer\domains\example\vendor\nesk\rialto\src\ProcessSupervisor.php on line 307
```

⚠️ WITH "DEBUG MODE"
```php

$puppeteer = new Puppeteer([
    ...
    'debug' => true,
]);

```

```plaintext
Fatal error: 
    Uncaught Nesk\Rialto\Exceptions\Node\FatalException: 
    
    Protocol error (IO.read): Target closed. Error: Protocol error (IO.read): Target closed. at 
    C:\OpenServer\domains\example\node_modules\puppeteer\lib\cjs\puppeteer\common\Connection.js:208:63 at new Promise (<anonymous>) 
    at CDPSession.send (C:\OpenServer\domains\example\node_modules\puppeteer\lib\cjs\puppeteer\common\Connection.js:207:16) 
    at Object.readProtocolStream (C:\OpenServer\domains\example\node_modules\puppeteer\lib\cjs\puppeteer\common\helper.js:249:39) 
    at async Page.pdf (C:\OpenServer\domains\example\node_modules\puppeteer\lib\cjs\puppeteer\common\Page.js:1192:16) 
    at async PuppeteerConnectionDelegate.handleInstruction (C:\OpenServer\domains\example\vendor\nesk\puphpeteer\src\PuppeteerConnectionDelegate.js:36:21) in C:\OpenServer\domains\example\vendor\nesk\rialto\src\ProcessSupervisor.php:307 
    
    Stack trace: 
        
        #0 C:\OpenServer\domains\example\vendor\nesk\rialto\src\ProcessSupervisor.php(423): Nesk\Rialto\ProcessSupervisor->checkProcess in C:\OpenServer\domains\example\vendor\nesk\rialto\src\ProcessSupervisor.php on line 307
```
